### ISSUE TITLE
installed  code shouldn't reference desiconda/current

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#104]
A path problem for the 18.2 install, which we need to fix for 18.3:

```
[cori10 ~] source /project/projectdirs/desi/software/desi_environment_18.2.sh  
[cori10 ~] echo $DESICONDA
/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda
[cori10 ~] which desi_extract_spectra 
/global/common/software/desi/cori/desiconda/current/code/desispec/0.18.0/bin/desi_extract_spectra
[cori10 ~] head $(which desi_extract_spectra )
#!/global/common/software/desi/cori/desiconda/current/conda/bin/python
# EASY-INSTALL-SCRIPT: 'desispec==0.18.0','desi_extract_spectra'
__requires__ = 'desispec==0.18.0'
__import__('pkg_resources').run_script('desispec==0.18.0', 'desi_extract_spectra')
```

Note that those are in terms of desiconda/current instead of desiconda/20180130-1.2.4-spec .  Right now those are the same, but when we update which version of desiconda is "current" it will change the underlying desiconda version used when someone configures 18.2.  For 18.3, we should make sure that all the paths use desiconda/20180130-1.2.4-spec and don't rely upon "current".

As a procedure, I hope this is as simple as configuring desiconda/20180130-1.2.4-spec instead of desiconda/current before proceeding with installations.  It would be extra helpful if desiInstall could resolve symlinks into their final non-symlinked path; unfortunately `os.path.abspath` doesn't do that.

**Comment by weaverba137** [comment]
It's `os.path.realpath()` that's needed here.

**Comment by weaverba137** [comment]
This is going to be quite a bit trickier than I thought.  The problem is that desiInstall *already* uses `sys.executable` as the path to the Python executable, and that value is set *correctly*, at least for release 18.2 and 18.2a:
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/bin/python'
>>> 
```

**Comment by weaverba137** [comment]
@sbailey Does the `#!` line have this problem for *every* executable script in 18.2 and 18.2a, or only some, or just the one?

**Comment by sbailey** [comment]
It appears to be a problem for every python executable script installed in 18.2 and 18.2a.  I haven't found any counter examples.

How does "python setup.py install" even know about "current" if the path to the python script does not?

**Comment by weaverba137** [comment]
I need to run some tests, but it is possible that if `#!/.../current/conda/bin/python` is in the header of desiInstall itself, then maybe `sys.executable` gets set to that.

**Comment by weaverba137** [comment]
OK, I've confirmed it.  When desiInstall has the header `#!/global/common/software/desi/cori/desiconda/current/conda/bin/python`, it installs with `/global/common/software/desi/cori/desiconda/current/conda/bin/python setup.py install`.

**Comment by weaverba137** [comment]
Aha!  The method `desiutil.install.DesiInstall.anaconda_version()` was using an outdated path to determine the desiconda version, and as a result, it was returning 'current'.  I'm still not entirely clear on how this translated into the executable name, but it's a clue.

**Comment by weaverba137** [comment]
The only think I can't figure out is how the bootstrap procedure failed to find the correct desiconda version  (20180130-1.2.4-spec) when it was initially installed.

**Comment by weaverba137** [comment]
And the mystery deepens, because on *edison* many scripts in "current" are actually installed with `#!/global/common/software/desi/edison/desiconda/20180130-1.2.4-spec/conda/bin/python`.  And on cori, desimodel/0.9.1 is installed with `#!/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/bin/python`.

So it is starting to look like it might come down to *who* installed these products and *when*.
