### ISSUE TITLE
desiInstall cleanup from a failure

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#106]
I just tried to install desimodel/0.9.4 before making the correct svn tag too.  desiInstall informatively told me
```
CRITICAL:install.py:829:get_extra:2018-03-29T17:42:45: Error grabbing extra data: svn: E170000: URL 'https://desi.lbl.gov/svn/code/desimodel/tags/0.9.4/data' doesn't exist
```
But it still left behind partially installed `/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/code/desimodel/0.9.4` and a 0.9.4 modulefile, which had to be manually removed before reinstalling (though at least the reinstall also told me that the old installation was in the way and what to remove).

It would be better if a failed installation would cleanup after itself.

Note: I have successfully made the right svn tag now and installed 0.9.4, so testing this will require a different tag.

**Comment by weaverba137** [comment]
I prefer to leave things behind for debugging purposes.  `desiInstall --force` is specifically designed to deal with existing files.  I'm currently trying to reduce the complexity of desiInstall, and tracking all the what is installed so it can be removed would add a fair bit of code.

**Comment by weaverba137** [comment]
@sbailey, do you have further comments on this?  If not, I consider this an already solved problem.

**Comment by sbailey** [comment]
OK we can close this as a feature not a bug.  At low priority, consider adding a warning message like

> WARNING: installation failed; partially installed files may be leftover in {versioned code installation directory} and {module file} and {temporary git checkout}.

i.e. without tracking exactly which ones are there or not, I'm guessing that the set of possible places could be enumerated as a warning for cleanup.
