### ISSUE TITLE
change declination range of equatorial/basemap projections?

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#114]
@dkirkby In `plots.plot_sky_binned` I'd like to change the declination range of the map to, e.g., to zoom into the southern or northern cap region.  I played around with the `lat_[0,1,2]` and `llcrnrlat` and `urcrnrlat` arguments to the `Basemap` class (around line 460 in `init_sky`) but didn't have much luck.

This request may not be possible but I thought I'd ask.

**Comment by weaverba137** [comment]
Pinging @dkirkby.  This question/issue is for you.

**Comment by weaverba137** [comment]
It is not possible to change axis limits on built-in matplotlib projections.  Since we're trying to eliminate basemap and related external dependencies, we're not going to support that *in desiutils*.  You are welcome to share other solutions you find with the collaboration.
