### ISSUE TITLE
problem with dust.SFDMap: 'Column' object has no attribute 'galactic'

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#117]
```python
from astropy.table import Table, Column
tt = Table()
tt.add_column(Column(name='ra', data=[120, 270, 310], unit='degrees'))
tt.add_column(Column(name='dec', data=[1.0, 5.0, 3.0], unit='degrees'))
from desiutil.dust import SFDMap
SFDMap.ebv(tt['ra'], tt['dec'])

----> 6 SFDMap.ebv(tt['ra'], tt['dec'])

~/repos/desihub/desiutil/py/desiutil/dust.py in ebv(self, *args, **kwargs)
    260 
    261         # ADM extract Galactic coordinates from astropy
--> 262         l, b = c.galactic.l.radian, c.galactic.b.radian
    263 
    264         # Check if l, b are scalar. If so, convert to 1-d arrays.

AttributeError: 'Column' object has no attribute 'galactic'
```

**Comment by moustakas** [comment]
I also get this error when I pass just numpy arrays of RA and Dec, which seems awfully fragile, e.g.,

The documentation states:
> coordinates : :class:`~astropy.coordinates.SkyCoord` or :class:`~numpy.ndarray`
>     If one argument is passed, assumed to be an :class:`~astropy.coordinates.SkyCoord`
>     instance, in which case the ``frame`` and ``unit`` keyword arguments are
>     ignored. If two arguments are passed, they are treated as
>     ``latitute, longitude`` (can be scalars or arrays or a tuple), in which
>     case the frame and unit are taken from the passed keywords.

However, passing numpy arrays and explicitly setting the units and the frame of reference, e.g.,
```
SFDMap.ebv(tt['ra'].data, tt['dec'].data, unit='degrees', frame='icrs')
```
still crashes with the same error.  

@geordie666 Can you take a peak or am I not understanding something?

**Comment by geordie666** [comment]
I'll take a look this afternoon. I tested this with columns read from FITS files, but not explicitly with tables, but I don't understand this at first glance.

**Comment by geordie666** [comment]
My original test case still works:

```
from astropy.table import Table, Column
tt = Table()
tt.add_column(Column(name='ra', data=[120, 270, 310], unit='degree'))
tt.add_column(Column(name='dec', data=[1.0, 5.0, 3.0], unit='degree'))
from desiutil import dust
dust.ebv(tt['ra'], tt['dec'])
```
So it's failing because of something to do with instantiating the class. Let me dig further.

**Comment by geordie666** [comment]
Might be a different issue, but let's fix it anyway. Should be a quick fix. I'll try to do it soon.

**Comment by moustakas** [comment]
This error arose from my non object-oriented upbringing.  Apologies for the noise.  

Created a new issue regarding `mapdir` in #118.
