### ISSUE TITLE
default mapdir assumed by dust.SFDMap won't jive with $DUST_DIR

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#118]
In https://github.com/desihub/desimodules/issues/22 we added a new $DUST_DIR environment variable to point to `/global/project/projectdirs/cosmo/data/dust/v0_1`

However, `dust.SFDMap` needs/wants the full path to the dust maps, i.e., 
`/global/project/projectdirs/cosmo/data/dust/v0_1/maps`.

Specifically, at NERSC:
```
from desiutil.dust import SFDMap
ss = SFDMap()
ss.mapdir
  '/global/project/projectdirs/cosmo/data/dust/v0_1' # comes from $DUST_DIR
ss.ebv(120, 1.0)
[snip]
FileNotFoundError: [Errno 2] No such file or directory: '/global/project/projectdirs/cosmo/data/dust/v0_1/SFD_dust_4096_ngp.fits'
```
but
```
from desiutil.dust import SFDMap
ss = SFDMap(mapdir='/global/project/projectdirs/cosmo/data/dust/v0_1/maps')
ss.ebv(120, 1.0)
```
works.

So I think that `SFDMap.__init__` just needs to append the `maps` subdirectory when evaluating `$DUST_DIR` (which I *don't* think we should change).

**Comment by weaverba137** [comment]
Fixed by #119.
