### ISSUE TITLE
Change default log level

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiutil#127]
Quoting from the docs:
```
This module is intended to support three different logging use patterns:
...
3. Change the default log level on the command-line. This can actually be accomplished in two ways: 
   the command-line interpreter can call get_logger() with the appropriate level, or the environment 
   variable DESI_LOGLEVEL can be set.
```
The second way works for me using:
```
os.environ['DESI_LOGLEVEL'] = 'DEBUG'
log = desiutil.log.get_logger()
assert log.level == 10
```
However, the first way does not seem to accomplish the same thing, with the second assertion failing:
```
log1 = desiutil.log.get_logger(desiutil.log.DEBUG)
assert log1.level == 10
log2 = desiutil.log.get_logger()
assert log2.level == 10
```

**Comment by dkirkby** [comment]
Never mind: I was testing with an older version of desiutil.  Closing.

**Comment by weaverba137** [comment]
I can't reproduce this:
```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import desiutil.log as l
>>> log1 = l.get_logger(l.DEBUG)
>>> assert log1.level == 10
>>> log2 = l.get_logger()
>>> assert log2.level == 20
```
Are you quite certain that when you did the second test, that `DESI_LOGLEVEL` was not set in the environment?

**Comment by dkirkby** [comment]
I am finding `log2.level == 20`: do we agree on that?

**Comment by weaverba137** [comment]
Yes.

**Comment by dkirkby** [comment]
I expected all calls to `get_logger()` after the initial `get_logger(DEBUG)` to have `level == 10`, since this is documented as a method to change the default log level.

**Comment by weaverba137** [comment]
@dkirkby, I don't think this is worth fixing in *code*, because I don't want to fool around with a low-level library that is widely used.  However, if you thing the *documentation* could be improved, I can certainly work on that.

**Comment by weaverba137** [comment]
No one seems to care about this anymore, closing without any action.
