### ISSUE TITLE
plot_sky_binned does not show any data

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#129]
I'm just starting out with this and maybe I'm making a newbie mistake, but the code below should show a "bright" spot at RA, Dec = (0, +30), but it just shows a uniform solid sky.

```python
RA = np.random.normal(loc=0.0, scale=5.0, size=(10000,))
Dec = np.random.normal(loc=30.0, scale=5.0, size=(10000,))
ax = plot_sky_binned(RA, Dec, max_bin_area=2.0, verbose=True)
plt.savefig(os.path.join(os.environ['HOME'], 'Downloads', 'test_plot.png'))
```
![test_plot](https://user-images.githubusercontent.com/3780690/50478449-0fd1e080-09c9-11e9-98e5-9f7665936cb4.png)

numpy = 1.15.4
matplotlib = 3.0.2
basemap = 1.2.0
desiutil = master

**Comment by weaverba137** [comment]
The example *does* work with 

numpy = 1.13.3
matplotlib = 2.1.2
basemap = 1.0.7

which is what we have in the DESI stack at NERSC.  Although running this code there produces lots of scary warnings:
```
global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:1623: MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.
  fill_color = ax.get_axis_bgcolor()
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3222: MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
  b = ax.ishold()
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3231: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  ax.hold(b)
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3413: MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
  b = ax.ishold()
/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3422: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  ax.hold(b)
```

@dkirkby, if not you, who is responsible for keeping this code up-to-date with matplotlib?

**Comment by weaverba137** [comment]
P.S. when `plot_sky_binned()` prints extra information: `Using 52 x 159 grid in cos(DEC) x RA with pixel area 4.989 sq.deg.`.  Are we certain that's `cos(DEC)`?  It is not `sin(DEC)`?

**Comment by dkirkby** [comment]
The scary warnings are produced by basemap, not desiutil AFAIK.  Perhaps updating basemap in desiconda would fix this?

**Comment by weaverba137** [comment]
No, because as I've already demonstrated, newer versions don't work *at all*.

**Comment by weaverba137** [comment]
This will be fixed in the basemap replacement branch to be merged soon.
