### ISSUE TITLE
Replace basemap

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiutil#132]
This issue is to replace the use of basemap in this package with a pure-matplotlib implementation of the map projection, to resolve #129.

Note that matplotlib already has built-in support for some  all-sky projections:
```
matplotlib.projections.get_projection_names()
['aitoff', 'hammer', 'lambert', 'mollweide', 'polar', 'rectilinear']
```

**Comment by weaverba137** [comment]
Researching alternatives:

* [basemap was deprecated in favor of cartopy in 2016](https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement).
* However [cartopy](https://scitools.org.uk/cartopy/docs/latest/) has a fairly hefty list of [dependencies](https://scitools.org.uk/cartopy/docs/latest/installing.html#requirements), many of which are not Python packages.
* Let's see how far we can get with just the matplotlib built-ins.

**Comment by weaverba137** [comment]
I noticed a bug in `plot_grid_map()`, that I'm recording here for reference.  If you look at the original notebook that accompanied this code, `doc/nb/SkyMapExamples.ipynb`, in [the example plot](https://render.githubusercontent.com/view/ipynb?commit=c4029ce29aa8e2e70b1cf4097618fe83a29e7627&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f646573696875622f646573697574696c2f633430323963653239616138653265373062316366343039373631386665383361323965373632372f646f632f6e622f536b794d61704578616d706c65732e6970796e62&nwo=desihub%2Fdesiutil&path=doc%2Fnb%2FSkyMapExamples.ipynb&repository_id=40208831&repository_type=Repository#Map-Plotting), the projection edge passes through one of the grid values (that is, in between two edges).  That means the bins on the left edge of the plot are *the same bins* as the bins on the right edge of the plot.  That means they should have the same data value.  However, you can easily see by comparing colors along the two edges that they do not have the same value.
