### ISSUE TITLE
test_plots problems with basemap and latest desiconda at NERSC

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#134]
@weaverba137 and @dkirkby could I get some help with this?

Our latest desiconda installation at NERSC includes matplotlib 2.1.2 and basemap 1.2.0.  The environment is available via:
```
source /project/projectdirs/desi/software/desi_environment.sh test-master
```

**Background, perhaps unrelated**:

Tests of code using `mpl_toolkits.basemap` fail with:
```
  File "/global/common/software/desi/cori/desiconda/20190730-1.3.0-spec/code/desiutil/master/py/desiutil/test/test_plots.py", line 29, in <module>
    import mpl_toolkits.basemap
  File "/global/common/software/desi/cori/desiconda/20190730-1.3.0-spec/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 155, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/global/common/software/desi/cori/desiconda/20190730-1.3.0-spec/conda/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

https://github.com/matplotlib/basemap/issues/419 says that the problem is with the conda package, not with basemap itself, but regardless can be fixed by setting $PROJ_LIB = (anacondadir)/share/proj .  Trying this seems to work (maybe):
```
export PROJ_LIB=/global/common/software/desi/cori/desiconda/20190730-1.3.0-spec/conda/share/proj
```

**The blocking factor now**:

Now tests can get past the mpl_toolkits.basemap import, but get stuck in `desiutil.tests.test_plots.test_plot_slices` which uses up 10s of TB of memory until the OS kills it.  Curiously, running the equivalent commands from ipython seems to work fine.

I think this is unrelated to the PROJ_LIB problem.  Maybe.  But can you please help get desiutil tests passing on NERSC when using desiconda 20190730-1.3.0-spec ?

**Comment by weaverba137** [comment]
There are several problems with basemap that have already been identified: #132, #129, #114.  Perhaps we should stop using it altogether.

**Comment by sbailey** [comment]
PR #135 (for the test memory problems) plus adding $PROJ_LIB by hand to the desiconda module file (for the basemap import problem) worked around this issue.  Regardless, getting rid of basemap sounds good.  That is tracked in issue #132 so I'll close this now.
