### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by am610** [desihub/desiutil#138]
I am trying to install desiutils, in ubuntu. However the installation process is not clearly mentioned anywhere. can someone pelase elaborate the steps of installation ?
thanks
Ayan

**Comment by tskisner** [comment]
Most of the DESI stack uses commonly available python packages.  On Ubuntu, just create a virtualenv and then pip install dependencies there.  For example:
```
apt-get install python3 python3-pip virtualenv
```
Decide where to put your DESI software stack (e.g. $HOME/software/desi):
```
virtualenv -p python3 $HOME/software/desi
```
Now activate this environment:
```
source $HOME/software/desi/bin/activate
```
Now pip install common DESI dependencies (the fitsio version is to work around an install bug with the current default version):
```
pip install numpy scipy matplotlib astropy healpy fitsio==1.0.5
```
Now install desi packages from either git checkouts or directly from github:
```
cd /path/to/git/desiutil
pip install .
```
OR
```
pip install pip install https://github.com/desihub/desiutil/archive/master.zip
```
You can then install other desi packages too, for example:
```
pip install https://github.com/desihub/desitarget/archive/master.zip
pip install https://github.com/desihub/fiberassign/archive/master.zip
```
And of course if things get too out of date, just `rm -rf $HOME/software/desi` and repeat.

**Comment by weaverba137** [comment]
@am610 , in what context are you attempting to install desiutil?  I can't find any record of you being a DESI collaborator.  This package is highly specific to that project.

**Comment by weaverba137** [comment]
No response from the reporter, closing.
