### ISSUE TITLE
python setup.py test deprecated?

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#144]
While testing a new environment using python 3.6.10, I encountered the following:
```
[cori08 desiutil] python setup.py test
running test
WARNING: Testing via this command is deprecated and will be
removed in a future version. Users looking for a generic test entry
point independent of test runner are encouraged to use tox.
running egg_info
...
```
@weaverba137 please investigate our test runner pattern (this is broader than just desiutil).  tox is a 3rd party library so I'm not thrilled about bringing in another external dependency unless we really have to, but hopefully we can find a test runner pattern that isn't deprecated.  Thanks.

**Comment by weaverba137** [comment]
Note that this is actually a broader issue.  It's not just that `python setup.py test` is deprecated, it's `python setup.py` that's deprecated.

We originally borrowed almost all of our testing and CI infrastructure from astropy (although they continue to use the pytest framework instead of `unittest`).  They have moved more-or-less completely to using tox.  So if we *don't* use tox, it might be somewhat harder to find ready-made examples to borrow from.  I don't think it would be hard to invoke the `unittest` runner directly.

That said, one thing we can do immediately to start moving away from `python setup.py`  is use `sphinx-build` instead of `python setup.py build_sphinx`.

**Comment by weaverba137** [comment]
I think we have a winner:
```
python -m unittest discover -t py -v desiutil.test
```
Run this in the same directory as the `setup.py` file. For coverage checks:
```
coverage run -m unittest discover -t py -v desiutil.test
```
Please test on other packages.

**Comment by sbailey** [comment]
Thanks.  Although that does work, it doesn't exactly roll off the tongue as something that is easy to remember for how to run tests.  If we invoke tests through pytest or nosetests could there be a simpler invocation to remember?  Both of those are already in our environment due to one of our dependencies installing them, and could be lighter weight to use than tox.  Or maybe a small wrapper script would make that test recipe easier to remember.  Note: whatever the recipe is, it should also support running a subset of the tests (e.g. in this case, `python -m unittest discover -t py -v desiutil.test.test_stats` works to support running a subset of the desiutil tests).

Also: if `python setup.py` itself is deprecated, what's the equivalent of `python setup.py install`? 

Regarding tox: that seems a full featured test and deploy framework, but it looks like it uses virtualenvs with installed dependencies to get a guaranteed environment instead of testing within the context of the currently configured environment, which is often what I'm trying to do (e.g. testing fiberassign with a new version of desimodel before committing the files to anywhere that tox could install).

**Comment by weaverba137** [comment]
Is the goal here to keep the *output* of the test invocation as similar as possible to the current, or is it more important to type fewer characters?  In principle, pytest could work with our existing unittest-centered framework, but the output might look wildly different.

`pip install` (with many options) is the replacement for `setup.py install`.

Yes, that is an accurate assessment of tox.

**Comment by sbailey** [comment]
I'm fine with the output looking different as long as it runs all the tests and provides an equivalently useful report about what failed or not.  My main goal here is to have something that is easy to remember so that it won't be a barrier for people running tests.

**Comment by weaverba137** [comment]
Please try just running `pytest` in say a checkout of desispec.  It does appear to automatically find all the tests.

**Comment by weaverba137** [comment]
I will recommend that if we go the route of `pytest` that we install `pytest-cov`, so that the coverage check becomes `pytest --cov`.

**Comment by sbailey** [comment]
Well, that is certainly easier to remember.  Sounds good.  +1 for including `pytest-cov`.  Let's use this as our standard testing method for awhile and see if any gotchas pop up.

**Comment by sbailey** [comment]
And for the record: `pytest py/desiutil/test/test_census.py` is the syntax for running the subset of tests in `test_census.py`.  Nice and easy.

Note: next time we've overhauling travis tests let's update to using pytest, but I think we can close this ticket for now.
