### ISSUE TITLE
support for astropy 4.2?

### ISSUE THREAD

**Issue by julienguy** [desihub/desiutil#158]
I know there is a requirement to have astropy<4.1, but I am able to run with astropy 4.2 , provided
I disable the mention to astropy._erfa.core.ErfaWarning
( in https://github.com/desihub/desiutil/blob/b83c2d2154c3be86679f3c1a6f08ce3e604bc695/py/desiutil/iers.py#L121 )

**Comment by weaverba137** [comment]
Could you please submit a PR that fixes that?

Are we planning to support 4.2 (which is *not* a long-term support release) in release 20.12?

**Comment by julienguy** [comment]
I have it in a branch (dirac) but I am not sure this is the best way to deal with the issue. Maybe we can test the astropy version. Can you (@weaverba137) please have a look at it and make the changes you think are necessary? I will let @sbailey answer on the long term support.

**Comment by weaverba137** [comment]
Thanx, I'll take a look.

**Comment by sbailey** [comment]
20.12 will continue to use 4.0.1.post1 that is in the current NERSC desiconda installation.

At the same time, for our major dependencies (numpy, scipy, astropy, fitsio) we should make an effort to support whatever the latest version is that someone would get by doing a "conda install ..." or "pip install ..." of that package.  I don't think we need to put a lot of effort into making sure that our unit tests specifically check that every time, but when we come across cases like this (astropy 4.2 incompatibility) we should try to fix it when possible.

**Comment by weaverba137** [comment]
@julienguy, do you have more work to do on the `dirac` branch?  If not, I'll update the unit tests and convert that to a PR.

**Comment by julienguy** [comment]
Please go ahead. Thanks!

**Comment by sbailey** [comment]
Fixed in PR #159.  Closing.
