### ISSUE TITLE
dust corrections in imaging catalogs vs using desiutil.dust do not match

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#165]
@schlafly @julienguy @segasai @sbailey @djschlegel 

We may want to flag this ticket as TSTC (*too small to care*) but it bugs me and so I'm reporting it.

The issue is that the photometric dust corrections one derives using the nominal DESI extinction curve (O'Donnel), the tools in `desiutil.dust`, and the filter curves in `speclite` do not match the static values in the imaging catalogs (at the <<1% level, although the effects will be larger in dustier regions, of course).

```
source /global/cfs/cdirs/desi/software/desi_environment.sh master
ipython
```
Then:
```
import numpy as np
from astropy.table import Table
from desiutil.dust import SFDMap, ext_odonnell
from speclite import filters

filters = filters.load_filters('decam2014-g', 'decam2014-r', 'decam2014-z', 'wise2010-W1', 'wise2010-W2')

allobj = Table.read('/global/common/software/desi/cori/desiconda/current/code/desitarget/master/py/desitarget/test/t/sweep-310m005-320p000.fits')

RV = 3.1
SFD = SFDMap(scaling=0.86) # SF11 recalibration of the SFD maps
klam = RV * ext_odonnell(filters.effective_wavelengths.value, Rv=RV)
bands = ['G', 'R', 'Z', 'W1', 'W2']

for obj in allobj:
    ebv = SFD.ebv(obj['RA'], obj['DEC'])
    desiutil_trans = 10**(-0.4 * ebv * klam)
    imaging_trans = np.array([obj['MW_TRANSMISSION_{}'.format(band)] for band in bands])
    print(desiutil_trans-imaging_trans)

[ 0.0046744  -0.00197977 -0.00130079  0.00218582  0.00144951]
[ 0.00452608 -0.00191081 -0.00125241  0.00209959  0.00139206]
[ 0.00452687 -0.00191123 -0.00125267  0.00210005  0.00139237]
[ 0.00465634 -0.00197157 -0.00129498  0.00217536  0.0014425 ]
[ 0.00462627 -0.0019557  -0.00128392  0.00215694  0.00143028]
[ 0.00466479 -0.00197326 -0.00129628  0.0021793   0.00144518]
```

I'm fairly certain the differences arise from what we adopt as the filter-dependent extinctions in the imaging catalogs--
  https://github.com/dstndstn/tractor/blob/master/tractor/sfd.py#L23-L35
```
    extinctions = {
        'SDSS u': 4.239,
        'DES u': 3.995,
        'DES g': 3.214,
        'DES r': 2.165,
        'DES i': 1.592,
        'DES z': 1.211,
        'DES Y': 1.064,
        'WISE W1': 0.184,
        'WISE W2': 0.113,
        'WISE W3': 0.0241,
        'WISE W4': 0.00910,
```
vs
```
[print('{}: {:.5f}'.format(band, kl)) for band, kl in zip(bands, klam)]
G: 3.63476
R: 2.55809
Z: 1.43322
W1: 0.17459
W2: 0.10540
```

**Comment by schlafly** [comment]
Sorry, I need to look at this in more detail, but quickly: I agree with you that we don't expect especially good agreement here, since the imaging assumes a Fitzpatrick (1999) extinction curve.

**Comment by schlafly** [comment]
I need to work on the 0.1% survey, but please see
cori:~schlafly/projects/dust/python/dust.py
There's a function fm_unred which is a ~mechanical translation of the F99 extinction curve into python.  Then there's a function af99 that wraps this in an interface that's closer to the ext_odonnell interface.

**Comment by sbailey** [comment]
Documenting discussion / decisions from the data telecon this morning:
  * 0.1% (sv2) takes priority, but we want to standardize dust usage shortly after that to include in the denali rerun before starting the 1% (SV3) survey
  * We'll use Fitzpatrick (1999) extinction curve to match imaging surveys
    * unit tests should confirm that they match selected cases from the tractor outputs
  * `desispec.scripts.stdstars.dust_transmission` and `desispec.tsnr.dust_transmission` will be merged and moved to `desiutil.dust`.  These are wavelength-dependent, as opposed to `desiutil.dust.mwdust_transmission` which is integrated over a filter.
  * Codes will use SFD E(B-V) as input to match the EBV column in the tractor/targeting catalogs, and the 0.86 correction factor will be handled internally, i.e. not requiring the user to perform the conversion ahead of time

**Comment by geordie666** [comment]
Other points from this morning's data telecon:
   - Any scaling corrections to the dust maps should occur in individual functions, _not_ in the [SFDmap class](https://github.com/desihub/desiutil/blob/3ce49f0804fb824dcfa35d5c7e553c1f76565de8/py/desiutil/dust.py#L328) which should retain the [scaling kwarg](https://github.com/desihub/desiutil/blob/3ce49f0804fb824dcfa35d5c7e553c1f76565de8/py/desiutil/dust.py#L357-L358).
   - @segasai and I have developed [the same function](https://github.com/desihub/desispec/blob/c95b042d8c2204d4f4d7eb5375176d43a5acf9ee/py/desispec/scripts/stdstars.py#L115) in [two different places](https://github.com/desihub/desitarget/blob/4fc5e72b7c5c9069d9fad9eeab0945f2702f773f/py/desitarget/gaiamatch.py#L194) to correct Gaia-only sources for extinction. It may be worth merging those in `desiutil.dust`.

**Comment by moustakas** [comment]
I believe this issue was dealt with in #169.
