### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by ngbusca** [desihub/desiutil#17]
Hi! 
While trying to install desiutil I get the following error message:

File "/Users/ngbusca/Boulot/DESI/github/desiutil/py/desiutil/setup.py", line 19, in <module>
    from setuptools.compat import PY3
ImportError: No module named compat

I've checked independently and indeed, setuptools doesn't have a module named compat.

Any ideas?
Thanks!
Nicolas

**Comment by weaverba137** [comment]
What is your system, version of Python (including the full path to the python executable), and version of setuptools?

**Comment by ngbusca** [comment]
I'm on an OSX 10.11.2 (El Capitan)
which python gives:
/Library/Frameworks/EPD64.framework/Versions/Current/bin/python

python --version gives:
Python 2.7.3 -- EPD 7.3-2 (64-bit)

setuptools 19.4

**Comment by weaverba137** [comment]
You're using a *very* new setuptools with a *very* old Python.  That's a dangerous combination.

Still this is a minor problem with desiutil, so we will eventually fix this.  In the meantime, I recommend using an 18.x version of setuptools.

**Comment by ngbusca** [comment]
What is the recommended python version? I have plenty of python 2.7 code and I'm reluctant to move to python 3 and have it not work anymore.

I've commented out the line 19 of desiutil/py/desiutil.setup.py (from setuptools.compat import PY3) and the setup finishes without errors. I'm not sure whether this breaks something elsewhere...

**Comment by weaverba137** [comment]
The best practice would be to keep your personal versions as close as possible to the versions we have at NERSC. Currently we have Python 2.7.9, but any later version would be fine.

We *will* move to Python 3 soon!

**Comment by weaverba137** [comment]
This is fixed in desiutil/1.3.2.
