### ISSUE TITLE
tests failing on mac with modules

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#35]
I use modules on my mac; desiutil `python setup.py test` is failing with the following message:
```
======================================================================
FAIL: test_init_modules (desiutil.test.test_modules.TestModules)
Test the initialization of the Modules environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desiutil/py/desiutil/test/test_modules.py", line 105, in test_init_modules
    self.assertListEqual(modulecmd, ['/usr/bin/modulecmd', 'python'])
AssertionError: Lists differ: [u'/opt/modules/3.2.9/bin/modu... != [u'/usr/bin/modulecmd', u'pyth...

First differing element 0:
/opt/modules/3.2.9/bin/modulecmd
/usr/bin/modulecmd

- [u'/opt/modules/3.2.9/bin/modulecmd', u'python']
?     ------- -- ^^^^^^

+ [u'/usr/bin/modulecmd', u'python']
?       ^
```
I am confused because neither `/opt/modules/3.2.9/bin/modulecmd` nor `/usr/bin/modulecmd` exist on my machine and I'm not sure exactly what this test is testing.  Let me know if you need any info about my environment, modules installation, etc. to debug this.

**Comment by weaverba137** [comment]
This is straightforward to fix, but I need to know what the output of `which modulecmd` is on your machine.  Also, do you have the C version of Modules, or the all TCL version?

**Comment by weaverba137** [comment]
Ah, never mind, I can deduce that you have the C version installed, because the output of the test implies that `MODULE_VERSION` is set.

**Comment by weaverba137** [comment]
The latest commit on desiutil should fix this.  Please test.

**Comment by sbailey** [comment]
Yes, the latest version works fine.  Thanks.
