### ISSUE TITLE
Do we still need to copy the entire package to install directories?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#42]
Currently, when installing *tagged* software, desiInstall *both* performs `python setup.py install` *and* copies the contents of the GitHub (or similar) export to the final install directory.  Historically this was done so that data files not incorporated into the (Python) package would be in the install directory.  Subsequently we have moved to having data files internal to the Python packages, so for these, `python setup.py install` will be sufficient, and the copying of the contents is at best a duplication of files, and is also a place where things could break.

Obviously, for "master" installs, this is somewhat different.  We still need the copy, but in those cases, that's all we need.  We don't `python setup.py install` "master" installs.

**Comment by weaverba137** [comment]
PS, desimodel does still need data files copied, but there is a script for this that desiInstall understands, separate from the "copy the export" method.

**Comment by sbailey** [comment]
I think you are correct that desiInstall no longer needs to copy the entire package; "python setup.py install" is supposed to be self-contained and sufficient (except for desimodel).

I don't understand the comment about "master" installs, though.  Shouldn't `python setup.py install` also work even for non-tagged master branches too?

**Comment by weaverba137** [comment]
desiInstall *does not* run `python setup.py install` on "master" installs.  Instead it manipulates the module file so that `$PYTHONPATH` points to the `py/` directory instead of `lib/pythonX.Y/site-packages`.

**Comment by weaverba137** [comment]
PS, as always, http://desiutil.readthedocs.io/en/latest/desiInstall.html is recommended reading.  desiInstall is sufficiently complex that you should re-read that page every time desiInstall comes up in discussion.

**Comment by sbailey** [comment]
Although that feature of desiInstall may have originally been requested by me, now that "python setup.py install" does copy all the necessary data, is treating master as a special case still what we want?  The current method has the advantage that updating a "master" install as easy as "git pull", but that comes at the cost of code and conceptual complexity of desiInstall.  Maybe updating a "master" install should actually require rerunning "python setup.py install" too?

In the bigger picture, desiInstall has become more complicated than I had expected and much of that was probably driven by things that I advocated thinking that they would make it simpler.  You suggested one simplification in this original issue; I'm opening up the possibility of another (don't treat master as special).  Feel free to make other suggestions if they would help simplify the code.

For those who haven't been following the desiInstall history, the basic idea is that it installs the code *and* installs a module file to enable swapping back and forth between different versions.

**Comment by weaverba137** [comment]
Well, if you want to rewrite the integration test so that all the master checkouts work with `python setup.py install`, please go ahead!

**Comment by sbailey** [comment]
Top priority is getting desiInstall working again with the new anaconda + /global/common structure.  If updating the integration test cronjob is needed to change how master checkouts are updated, I'm happy to do that.  i.e. don't let this feature delay getting the rest working.

**Comment by tskisner** [comment]
For all of my work, I have been using "python setup.py develop --prefix=<blah>".  It sounds like that is not really supported, so I should probably use the "install" target rather than "develop".  Just have to remember to re-run that any time I modify my checkout during debugging :-)

**Comment by sbailey** [comment]
If "python setup.py install --prefix=..." works (it should), then "python setup.py develop --prefix=..." should work too.  I personally don't use it because any update that changes the version number breaks the development install and you have to run it again, and just putting py and bin into (PYTHON)PATH works.  But if you prefer development installs, you shouldn't have to avoid them.

For context, I'm not advocating "develop" installs for the master branch at NERSC because of the "if the version number changes it breaks the install" issue.  i.e. if we have to re-run install every time we do a git pull anyway just in case the version number changed, then we might as well do a normal install.  But develop installs could be useful in other contexts.

**Comment by weaverba137** [comment]
I've thought a bit more carefully about this, & will hold off on implementing this.  Enough packages need the contents of the etc/ directory copied to make changing this procedure more work than just turning it off.
