### ISSUE TITLE
desiInstall specex

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#49]
Update desiInstall and/or specex so that `desiInstall -v specex x.y.z` would work.  Currently it doesn't work because specex requires `SPECEX_PREFIX` to be set prior to `make install`, and desiInstall doesn't know that yet.

As the desi pseudouser on edison I ran `desiInstall specex 0.4.0` which failed with
```
desiInstall [desiutil.install.DesiInstall.get_options] Log - WARNING: The environment variable LANG is not set!
desiInstall [desiutil.install.DesiInstall.install] Log - CRITICAL: Error during compile: specex_boss_io.cc:73:2: warning: #warning needs to add jumps to legendre pol [-Wcpp]
 #warning needs to add jumps to legendre pol
  ^~~~~~~
specex_gauss_hermite_two_psf.cc:480:2: warning: #warning nasty hack to get rid off asap (i am sure it will last forever) [-Wcpp]
 #warning nasty hack to get rid off asap (i am sure it will last forever)
  ^~~~~~~
specex_linalg.cc:35:2: warning: #warning NEED TO FIX THIS ! [-Wcpp]
 #warning NEED TO FIX THIS !
  ^~~~~~~
specex_trace.cc:207:2: warning: #warning check meaning of fibermask [-Wcpp]
 #warning check meaning of fibermask
  ^~~~~~~
specex_psf_fit.cc:327:2: warning: #warning "need to know where to get xy ccd range info" [-Wcpp]
 #warning "need to know where to get xy ccd range info"
  ^~~~~~~
Makefile:27: *** SPECEX_PREFIX undefined.  Stop.
```

To fix this, I ran
```
cd /global/common/edison/contrib/desi/code/specex/0.4.0/
make clean
SPECEX_PREFIX=`pwd` make install
```

I also had to uncomment these lines in the installed 0.4.0 module file:
```
prepend-path PATH $PRODUCT_DIR/bin
prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
```
The following line was not commented out but isn't needed so I commented it out by hand:
```
prepend-path PYTHONPATH $PRODUCT_DIR/lib/python3.5/site-packages
```
specex does have a `etc/specex.module` file, but desiInstall is incorrectly identifying which pieces are needed or not for these lines:
```
{needs_bin}prepend-path PATH $PRODUCT_DIR/bin
{needs_python}prepend-path PYTHONPATH $PRODUCT_DIR/lib/{pyversion}/site-packages
{needs_trunk_py}prepend-path PYTHONPATH $PRODUCT_DIR{trunk_py_dir}
{needs_ld_lib}prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
{needs_idl}prepend-path IDL_PATH +$PRODUCT_DIR/pro
```
It's unclear to me why that choice is left to desiInstall instead of each product just including the lines that it actually needs, e.g. for specex
```
prepend-path PATH $PRODUCT_DIR/bin
prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
```

**Comment by weaverba137** [comment]
This is crazy.  I thought this had been fixed.  I have already successfully installed specex with desiInstall. Are you absolutely certain you are using the latest version of desiInstall AND specex?

**Comment by weaverba137** [comment]
This *has* been fixed.  The problem is that specex/0.4.0 doesn't contain the fix.  Why hasn't specex been tagged, since I fixed this back in September?

**Comment by sbailey** [comment]
I made a new tag of specex (0.4.1) which got further, setting SPECEX_PREFIX and successfully compiling, but it still produced an incorrectly installed module file including:
```
# prepend-path PATH $PRODUCT_DIR/bin
prepend-path PYTHONPATH $PRODUCT_DIR/lib/python3.5/site-packages
# prepend-path PYTHONPATH $PRODUCT_DIR/py
# prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
# prepend-path IDL_PATH +$PRODUCT_DIR/pro
```
Instead of 
```
prepend-path PATH $PRODUCT_DIR/bin
prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
```
What is the motivation for letting desiInstall derive the `{needs_*}` values?  Could we just update the `specex/etc/specex.module` file to just have the `prepend-path` lines that it needs?

**Comment by weaverba137** [comment]
The motivation is that someone can copy the module file template from desiutil and use it *with no further thought*.  This *was* a requirement that I had to implement at some point.

desiInstall scans the product directory and sets the `{needs_*}` values accordingly.  Because the specex GitHub code does not contain a top level `bin/` or `lib/` directory, it does not set those.  However, it does detect the top level `python/` directory and sets the module file accordingly.

Setting the PATH and LD_LIBRARY_PATH manually in the module file will get this working without any actual changes to desiInstall.  However, it means that the module file will diverge from being a minimally changed copy if desiutil.module.

**Comment by sbailey** [comment]
I updated the `specex/etc/specex.module` file, retagged as 0.4.2, and that works.  It is definitely useful to have an example module file as a starting point when creating a new product, but its ok if that needs to diverge a little bit on a product-by-product basis.
