### ISSUE TITLE
Add tests to the sklearn module

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#58]
The module `desiutil.sklearn` was added without any unit tests whatsoever.  A dummy module, `desiutil.test.test_sklearn` now exists as a placeholder to add these unit tests.

Assigning to @moustakas, since he added the module in the first place.

**Comment by weaverba137** [comment]
Sorry, by "now exists", I meant "as soon as #57 is merged".

**Comment by weaverba137** [comment]
@moustakas, do you have any test data that could be used to test this module?

**Comment by moustakas** [comment]
Apologies that I haven't gotten to this.  @belaa actually wrote a [test for the GMM sampler](https://github.com/desihub/desitarget/blob/master/py/desitarget/test/test_sample.py) back in `desitarget` which could perhaps be adopted here in part or in whole?

**Comment by weaverba137** [comment]
Is the` GaussianMixtureModel` class only used by desitarget?  I'm trying to understand why it is in desiutil and not desitarget.

**Comment by moustakas** [comment]
It is also used by desisim. I thought I mentioned this in my original PR.

**Comment by weaverba137** [comment]
Please disregard the previous question, I see the answer in #54.

Additional documentation of this module would be really nice too.
