### ISSUE TITLE
requested enhancements to plots.py

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#68]
The `desiutil.plots` module is fantastic but for QA it would be helpful if the following enhancements could be implemented:
* In `plot_sky_binned` (and possibly elsewhere) could `grid_data` be returned to the user?  For example, in addition to the skymap I'd like to separately look at the (pixelized) target densities (e.g., to make a histogram of the values stored in `grid_data`).  I could of course call the snippet of healpy code myself but that would be duplicating code.

* More challengingly is the question of how to deal with edges in the skymap (and the resulting target densities).  For example, if the input catalog doesn't fully span an edge pixel then the target density will be underestimated since it's being divided by the same area as the fully populated pixels.  The solution to this may be non-trivial and outside the scope of this module but nevertheless it would be great to solve this so that the QA is as useful as possible.

**Comment by moustakas** [comment]
I believe that @geordie666 is tackling the second requested feature as part of his targeting QA effort (https://github.com/desihub/desitarget/issues/21).  Along these lines, this notebook by @dkirkby should be very useful, as it shows how to generate a set of random points given a set of healpix pixels -- 
  https://nbviewer.jupyter.org/gist/anonymous/3625c69cd642d37cc9b3c6f4aaf86749

My thinking was to do the following for a wide range (all?) of nside values:
1. Find all the healpixels in the DESI footprint using `desimodel.footprint.tiles2pix`.
2. Throw down a large number of random points in these healpixels using @dkirkby's method.
3. For each healpixel, use `desimodel.footprint.is_point_in_desi` to find the fraction of random points in our footprint.  Store this weight in a light-weight FITS table which will be included in `desiutil`.
4. Read, cache, and use these weights by default when calling `plot_sky_binned`.

@geordie666 may have a different approach but this was my thinking.

**Comment by geordie666** [comment]
Yeah, I started looking at this and I'll finish it this week. For all the pixels in the (~14k sq. deg.) DESI footprint, @dkirkby's approach isn't much quicker than populating the entire sphere at relevant declinations. But, I think I can populate just the fractional pixels (i.e. the pixels that are partially in and partially out of the DESI footprint). Then things are much faster.

**Comment by geordie666** [comment]
Oh, I should add that we don't need to do this for a wide range of `NSIDE` values, just some high `NSIDE` (say `NSIDE` == 256). 

At resolutions with lower values of `NSIDE`, the fractional weight correction is simply the mean of the fractional weights for the pixels that are comprised of the higher-`NSIDE` pixels (because the pixels are equal-area, the denominators in the density calculation are always the same).

**Comment by weaverba137** [comment]
@geordie666, is this issue solved by desihub/desitarget#210, or is there additional work to do?

**Comment by geordie666** [comment]
The second bullet point is solved in desihub/desitarget#210, the first bullet point (returning `grid_data` to the user) is not

**Comment by weaverba137** [comment]
OK, I think PR #85 fixes that.

**Comment by geordie666** [comment]
For general reference, an example of how to solve bullet point 2 using the `desimodel` HEALPixel weights file is here:

https://github.com/desihub/desitarget/blob/master/py/desitarget/QA.py#L1329-L1341
