### ISSUE TITLE
generate and return an imaging-style "brick information" table or dictionary

### ISSUE THREAD

**Issue by moustakas** [desihub/desiutil#71]
The output of `brick.Bricks()` is not in the most useful format.  It would be useful to add a method that converts the `brick.Bricks` attributes into something that looks like a flat, imaging-style "brick information" structure, with `ra`, `dec`, `ra1`, `ra2`, `dec1`, `dec2`, etc. numpy arrays.

Bonus!  The code to do this already exists in `desitarget.mock.build.BrickInfo.generate_brick_info`! (Approximately [here](https://github.com/desihub/desitarget/blob/sky-and-QA/py/desitarget/mock/build.py#L96-L143), although this is on a branch that will be merged soon...)

**Comment by weaverba137** [comment]
@sbailey, I seem to recall there were numerical differences between bricks generated by what is now `desiutil.brick` versus bricks generated elsewhere (in IDL?). Did that get resolved?

In other words, I'm concerned about possible differences between brick tables generated with this method versus read from FITS files produced in other code(s).

**Comment by sbailey** [comment]
I don't believe those have been resolved.  A first step would be to compute the output from generate_brick_info (from John's branch or directly merged into this class) with the brick definition file from http://portal.nersc.gov/project/cosmo/data/legacysurvey/dr3/survey-bricks.fits.gz and then document and track down differences.  Doing so shouldn't be a blocking factor to moving John's code into this class, though it would be nice to get them resolved at the same time.

IIRC, the issue was something like bricks are named based upon truncating their central RA, but you can get slightly different floating point rounding from calculations like `center[i] = lowedge[i] + brickrowsize/2` vs. `center[i] = (np.arange(ncols)+0.5) * brickrowsize`

**Comment by weaverba137** [comment]
OK.  Is the 'dtiling' code in the DESI (decam/code) svn repository still the definitive source for the survey-bricks file?

**Comment by weaverba137** [comment]
Answering my own question: the survey-bricks.fits.gz file referenced above is a slightly earlier version of the bricks-0.25.fits checked in to the dtiling product.  The data are identical, the only difference being that the bricks-0.25.fits file includes the `AREA` column.

**Comment by weaverba137** [comment]
Please see the method `test_IDL_bricks` in py/desiutil/test/test_brick.py on the test-idl-bricks branch.  I've added some fairly stringent comparisons between the two calculations.  At this point I can't find anything that disagrees, *except* for the brick names.

Just noting: the IDL version uses `FLOOR()` to convert RA, Dec to brickname, while Python uses `int()`.
```
outdat[i].brickname = string(floor(ra_arr[i]*10), $
    pmvec[dec_arr[i] GE 0], floor(abs(dec_arr[i]*10)), $
    format='(i4.4,a1,i3.3)')
```
```python
            pm = 'p' if center_dec[i] >= 0 else 'm'
            dec = center_dec[i]
            names = list()
            for j in range(ncol_per_row[i]):
                ra = center_ra[i][j]
                names.append('{:04d}{}{:03d}'.format(int(ra*10), pm, int(abs(dec)*10)))
            brickname.append(names)
```

**Comment by weaverba137** [comment]
Further note:  as far as I can tell, where the brick names differ, they only ever differ in the RA portion of the name.  The Dec portion appears to always be identical.

**Comment by weaverba137** [comment]
More notes:  there are two methods of computing the RA centers:
```python
center_ra.append( 0.5*(edges[0:-1]+edges[1:]) )
```
and
```python
dra = edges[1]-edges[0]
center_ra.append(dra/2 + np.arange(ncol_per_row[i])*dra)
```
The later was commented out.  Both produce problems with the RA portions of the brick name.  But they produce *different* problems.  That is, the errors are in different places.

**Comment by moustakas** [comment]
Apologies for potentially mudding the water, but bricks are used in one more place: [skybrick](https://github.com/sbailey/skybrick/blob/master/skybrick.py).  

@apcooper used `skybrick` to assign the Galaxia mock objects to large (10x10 deg2) bricks and I in turn read the "brick information" structure (e.g., `$DESI_ROOT/mocks/mws/galaxia/alpha/v0.0.4/bricks.fits`) in `desitarget.mock.io`.  My hope is that the `brickname` algorithm in this code is consistent with `desiutil.brick.Bricks`, although I haven't explicitly checked.

**Comment by weaverba137** [comment]
@moustakas, good to know.  I think based on what I've seen so far, the brickname code would need to be rigorously tested.

This brings up another issue.  In the past we have said several times that the best way to proceed is "don't try to re-create the bricks, propagate them from targeting."  This request doesn't "feel" like following that advice.

Furthermore, the desitarget code mentioned originally just takes the data produced by `desiutil.brick.Bricks` and makes a table out of it.  You could do the exact same thing, more definitively and probably more quickly by just reading the survey-bricks.fits file linked to above.

To simplify `desiutil.brick.Bricks` somewhat, it creates brick data on the fly and provides methods for matching an arbitrary RA, Dec to a brick.  Why not read the brick data from a file, following the "don't try to re-create bricks" rule?

**Comment by geordie666** [comment]
There are multiple reasons that we might want to manipulate bricks beyond
reading in a file. For instance, observations are processed and restitched
along brick lines, so it makes sense to check for density changes along
those lines for QA purposes (what if a bright star spans a brick etc.).
What if LSS catalogs find brick-based patterns when comparing to random
catalogs?

There aren't necessarily enough sources in a 0.25 x 0.25 brick for QA
purpose,s though, so it's also useful to be able to move to bricks of
different sizes.

Philosophically, if there's a function to create brick information we
should supply it under the assumption that other people may use bricks even
though we're moving towards HEALPix. If a brick is defined for all time, it
should have a functional description that doesn't require reading in a file.

**Comment by weaverba137** [comment]
I have solved the brickname problem.  This snippet illustrates how to do it:
```python
pm = 'p' if dec >= 0 else 'm'
sdec = "{0:06.0f}".format(np.absolute(dec)*10000)
sra = "{0:07.0f}".format(ra*10000)
brickname = sra[0:4] + pm + sdec[0:3])
```
This allows numbers like 39.599999999999994 to be correctly converted to '0396' (note how this number is on an integer boundary when multiplied by 10).  Numbers not close to integer values are rounded too, but enough precision is preserved so that the name is still correct on truncation.

It is still possible that this wouldn't work for some pathological numbers, but I don't think this is likely to happen as long as bricksize >= 0.25, and this has been tested with bricksize = 0.25, 0.5, 1.0.

**Comment by weaverba137** [comment]
@moustakas, now that I've solved the brickname problem, I've gone back to look at the table generation code.  The *documentation* of the code says that the function is supposed to return a table covering a *region*, whereas the actual code simply generates a table with all the bricks.  Which is the actual functionality that you want?

**Comment by moustakas** [comment]
@weaverba137, thank you for the cycles on this and apologies for out-of-date documentation. Originally the function would (optionally) return information on bricks in a specified region of the sky but when I switched to healpix it was simpler to simply return information on *all* the bricks (which is the behavior I still need).
