### ISSUE TITLE
desiutil.brick initialization code contains a bad data copy.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#73]
@geordie666 were you responsible for this code in the `__init__()` method of `desiutil.brick.Bricks` (I assume ADM is you):
```python
        #ADM to calculate brick areas, we can't exceed the poles
        edges_dec_pole_limit = edges_dec
        edges_dec_pole_limit[0] = -90.
        edges_dec_pole_limit[-1] = 90.
```
`edges_dec_pole_limit` is not a copy of `edges_dec`, it is a *reference* to `edges_dec`.  If you subsequently try to verify that `edges_dec` is unchanged that fails:
```python
        #ADM to calculate brick areas, we can't exceed the poles
        edges_dec_pole_limit = edges_dec
        edges_dec_pole_limit[0] = -90.
        edges_dec_pole_limit[-1] = 90.
        assert edges_dec_pole_limit[0] != edges_dec[0]
        assert edges_dec_pole_limit[-1] != edges_dec[-1]
        # AssertionError!
```
Unfortunately when I try to fix this by doing `edges_dec_pole_limit = edges_dec.copy()`, tests start failing. What is going on here?

**Comment by geordie666** [comment]
Nice catch (I am ADM, so this copy vs. reference bug was my fault).

That the brick "vertices" are strictly within -90o <= Dec <= 90o is probably not a requirement of the code (what is a vertex of a brick is poorly defined at the poles). `edges_dec` is already allowed to exceed the poles.

I therefore suggest removing the following two lines in `test_brick`:

```
        b1 = b.brickvertices(0, 90)
        b2 = b.brickvertices(90, 90)
        print(b1,b2)
        self.assertTrue(np.all(b1 == b2))
        self.assertEqual(np.max(b1[:,0])-np.min(b1[:,0]), 360.)
        self.assertTrue(np.all(b1[:,1] <= 90.))      REMOVE THIS LINE OF CODE!!!                                                                                                                               

        b1 = b.brickvertices(0, -90)
        b2 = b.brickvertices(90, -90)
        print(b1,b2)
        self.assertTrue(np.all(b1 == b2))
        self.assertEqual(np.max(b1[:,0])-np.min(b1[:,0]), 360.)
        self.assertTrue(np.all(b1[:,1] >= -90.))      AND REMOVE THIS LINE OF CODE!!!      
```
Then the tests should pass. 

Let me know if you'd prefer that I did this.

**Comment by weaverba137** [comment]
Let me do that myself, because I also need to compare the vertices to the vertices derived from the IDL-produced brick files.

**Comment by weaverba137** [comment]
When I comment out the tests, and copy the data, the vertices generated by `desiutil.brick.Bricks` no longer matches the IDL brick vertices.  In other words, the correct computation of the vertices seems to depend on this bad copy.

**Comment by geordie666** [comment]
Then I think that instead of these lines of code:

```
        #ADM to calculate brick areas, we can't exceed the poles                                                                                                                                         
        edges_dec_pole_limit = edges_dec.copy()
        edges_dec_pole_limit[0] = -90.
        edges_dec_pole_limit[-1] = 90.
```

We need to write:

```
        #ADM to calculate brick areas and vertices, we can't exceed the poles                                                                                                                                         
        edges_dec[0] = -90.
        edges_dec[-1] = 90.
```

and then change this:

```
        #ADM integrate area factors between Dec edges and RA edges in degrees                                                                                                                        
        decfac = np.diff(np.degrees(np.sin(np.radians(edges_dec_pole_limit[i:i+2]))))
        rafac = np.diff(edges_ra[i])
```

to this:

```
        #ADM integrate area factors between Dec edges and RA edges in degrees                                                                                                                        
        decfac = np.diff(np.degrees(np.sin(np.radians(edges_dec[i:i+2]))))
        rafac = np.diff(edges_ra[i])
```

and then don't change any of the unit tests.

The result will be that `self._edges_dec` is limited to -90o < Dec < 90o, but it sounds like this is in agreement with the IDL version of the code.

I believe that this shouldn't break anything downstream, as the `brickvertices` function is the only function in `desiutil.brick.Bricks` that is using `self._edges_dec` and I can't see a DESI-related purpose to be near the poles.

**Comment by weaverba137** [comment]
That works!
