### ISSUE TITLE
tests fail on cori but not edison

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#75]
desiutil tests on master fail on cori but not on edison:
```
======================================================================
ERROR: setUpClass (desiutil.test.test_svn.TestSvn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/temp/desiutil/py/desiutil/test/test_svn.py", line 42, in setUpClass
    assert p.returncode == 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/temp/desiutil/py/desiutil/test/test_svn.py", line 61, in setUpClass
    rmtree(cls.svn_checkout_path)
  File "/global/common/cori/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/global/common/cori/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/sjbailey/temp/desiutil/py/desiutil/test/t/svn_test_co'

----------------------------------------------------------------------
Ran 88 tests in 27.534s

FAILED (errors=1, skipped=2)
```

To reproduce:
```
source /project/projectdirs/desi/software/desi_environment.sh master
module unload desiutil
git clone https://github.com/desihub/desiutil
cd desiutil
python setup.py test
```

**Comment by weaverba137** [comment]
Confirmed.

**Comment by weaverba137** [comment]
Aha, the system versions of `svn` and `svnadmin` are out of sync.  Currently the *system* versions of subversion are:

* edison
  - `/usr/common/software/bin/svn --version == 1.7.9`
  - `/usr/bin/svnadmin --version == 1.6.17`
* cori
  - `/usr/common/software/bin/svn --version == 1.7.22`
  - `/usr/bin/svnadmin --version == 1.8.10`

On cori, `svnadmin` creates an svn repository with a version that is incompatible with svn/1.7.22.

A temporary workaround is to do `module load subversion`.  That at least forces `svn` and `svnadmin` to be in sync.

**Comment by sbailey** [comment]
It's easy to add "module load subversion" to the nightly test cron script.  Should we also add it to desimodules?  i.e. will this ever matter to end users?  If we do add it to desimodules, at minimum we should wrap it with a check so that it is effectively "if subversion isn't already loaded, load it now" since loading an already loaded module generates an error.

**Comment by weaverba137** [comment]
Well, it is certainly pathological that the system svn versions are out of sync like this, *i.e.* it is reasonable to expect that they *would* be in sync anywhere except NERSC.

`svnadmin` is *only* used for testing the `desiutil.svn` module.  The user-facing code doesn't use it at all.

With that in mind, I would say that adding `module load subversion` to the test is the easiest way to deal with this.  I don't think this is sufficiently important to add to desimodules.  In particular, the *module* versions of subversion are not in sync on all NERSC systems (*i.e.* type `module avail subversion` on both cori & edison...).
