### ISSUE TITLE
What is happening with the durhamplots branch?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#82]
Are you planning do to any further work on this branch?  It appears that you made one trivial change, though you should document the fact that the function now returns more than one value.

**Comment by forero** [comment]
I believe I won't add new changes (now that I've left Durham). I will document and start a PR.

**Comment by weaverba137** [comment]
Can we get this done?  Should take 10 minutes of work at most.

**Comment by forero** [comment]
Done. I am just waiting for @dkirkby to review that tiny change and be sure that I am not breaking something important.

**Comment by weaverba137** [comment]
Excellent, thank you.

**Comment by weaverba137** [comment]
Closed by #85.
