### ISSUE TITLE
What is happening with the healpix-weights branch?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#83]
The healpix-weights branch is three months old.  What is happening with this branch?  Can you describe exactly why this needs to be in desiutil, versus, say desimodel?

If you plan to continue to develop this branch.  Please move the script code into a Python module, so that it can be unit-tested.  Ideally the command line script should contain something like:
```
#!/usr/bin/env python
from sys import exit
from desiutil.healpix import main
exit(main())
```
See the desiInstall script.

**Comment by moustakas** [comment]
I'll delete the branch.  I started mucking around with this idea during the collaboration meeting but @geordie666 ended up incorporating something in https://github.com/desihub/desitarget/pull/210.
