### ISSUE TITLE
bootstrapping desiutil & desimodules into new conda environment

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#88]
We need a way to install a new set of desiutil, desimodules, etc. into a new desiconda environment, e.g.  /global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/ .  The previous instructions at https://desi.lbl.gov/trac/wiki/Pipeline/Install don't work anymore.

A couple issues to keep in mind [this replicates some emails, but I didn't find a ticket with the same info to reference...]

The base directory (/global/common/software/desi/cori/) keeps changing on us.  Each time we think this is the last time, but it probably won't be, so it shouldn't hard coded.  The previous top-level location was /global/common/cori/contrib/desi/ (which NERSC has asked us to migrate away from), but I don't think we ever got that into a fully working example of the directory structure we wanted, so don't take it too literally if it doesn't make sense.

We originally thought that we could decouple desiconda installations from desiutil, desispec, etc. installations, but that didn't work out, requiring that after every new desiconda install (e.g. to upgrade numpy/scipy/astropy/...) we need to reinstall all the desi packages.  i.e. bootstrapping the environment is no longer a rare case to be handled by a single expert; it will be a several-times-a-year thing.

I think we converged on this structure underneath a {basedir}, but I don't think we ever got an example fully fleshed out:
```
desiconda/{version}/
    conda/            - conda packages
    aux/              - compiled libraries releated to this desiconda release
    modulefiles/      - module files for desi packages
        {package}/
            {pkgversion}
startup/
    modulefiles/
        desimodules/  - module files defining sets of desiconda + other packages
            {desimodule_version}
```

Since desimodules picks a desiconda version + a self-consistent set of desispec, desisim, redrock, specsim, etc. packages, its modules file should live *outside* the structure for a single desiconda.  Conversely, since the installation for desiutil/desispec/specsim/etc. is tied to a particular desiconda release, modulefiles for installations tied to that release are contained within that release.

In the end, desi_environment.sh would
```
module use {basedir}/startup/modulefiles
module load desimodules/{version}
```

and `desimodules/{version}` would in turn:
```
module use {basedir}/{desiconda-version}
module load desiconda
module load desiutil/{p.q.r}
module load desispec/{x.y.z}
module load desisim/{a.b.c}
...
```

**Comment by weaverba137** [comment]
@sbailey, the directory tree presented here is slightly different from what we actually have on /global/common.  Basically, the startup directory is *under* desiconda:
```
desiconda/
    {desiconda-version}/
        aux/
        conda/
        modulefiles/
            desiconda/
                {desiconda-version}
    startup/
        modulefiles/
            desimodules/
                {desimodules-version}
```
The startup files still live *outside* of any specific *version* of desiconda.

Based on this structure, `desimodules/{desimodules-version}`, would do
```
module use {basedir}/desiconda/{desiconda-version}/modulefiles
module load desiconda
...
```

**Comment by sbailey** [comment]
Thanks for the directory structure correction.  Agreed.  I'll also add the note that under `desiconda/{desiconda-version}/modulesfiles/` is where other desispec, desisim, etc. module file directories would go.

I also forgot to note that `desiconda/{desiconda-version}/code/{package}/{pkgversion}/` is where the code would go for desispec, desisim, etc.

**Comment by weaverba137** [comment]
@sbailey, while peering into `/global/common/software/desi`, I see the directory `coriknl`.  Is that going to stick around, or should I ignore that?

**Comment by weaverba137** [comment]
@sbailey, @tskisner 

While testing the bootstrap install on edison, I found a couple of problems.
```
desi@edison01[1144]$ /global/common/software/desi/edison/desiconda/20170920-1.2.0-spec/conda/bin/python
Python 3.6.2 |Intel Corporation| (default, Aug 15 2017, 16:14:26)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
>>>
```
First of all, I don't think we're actually on to Python 3.6 yet.  Second, it's *really* nice to have readline support in Python.

**Comment by sbailey** [comment]
+1 for wanting readline.

From an email from Ted about coriknl:
> There are 2 things I'm doing differently currently in my knl-specific installation:
> 
> 1.  Use IDP rather than stock anaconda.  I think this is pretty important for KNL in order to pick up Intel optimizations of numpy (not just newer MKL), although I don't have specific numbers to back it up.
>
> 2.  Compile HARP and specex with the Intel compilers with avx512 optimizations enabled.  Based on a small test run, estimating a PSF with specex from one frame only took 15 minutes (32 processes / 2 threads per process) which is not really any slower than it took on edison.  I actually think that is pretty good!  Compare that to specter extractions, which timed out after 30 minutes on one frame (vs. ~20 minutes on edison)

We'll want to do more studies to quantify the differences of KNL-optimized python and compiled code installations, but coriknl is at least a placeholder that we may (likely will?) need to go in that direction.  For now I'd focus on the vanilla "cori" and "edison" versions, but it does imply eventually needing an option to override $NERSC_HOST when determining install directories.

**Comment by weaverba137** [comment]
OK, but what about Python 3.6?

**Comment by sbailey** [comment]
Python tends to be better about maintaining backwards compatibility with a minor version increase, so I expect that 3.6 will be fine.  i.e. it's not that we don't support 3.6, it just that we haven't tried and tested it.  This is in contrast to astropy 2.0 which we know doesn't work for us yet and will require us to make changes, or python 2.1 which we know is too old.  At the same time, we should avoid using 3.6-only features that would break 3.5 compatibility, which we do want to continue to support.

Regarding astropy 2: let's face that after the December workshop to maintain some stability between now and then, i.e. target it for the 18.4 (April 2018) desimodules release.

**Comment by weaverba137** [comment]
@sbailey, that's not my actual point.  I'm trying to say, why is it that *right now* the desiconda install on edison is Python 3.6?  Shouldn't it be 3.5, because that's still what we're targeting?

**Comment by sbailey** [comment]
@tskisner could answer more authoritatively, but for most of our dependencies we just grab the latest stable release unless we specifically know that we have to pin to an older version (like astropy).  Pegging to python 3.5 and grabbing the latest available numpy/scipy/matplotlib/etc would probably have also been fine.  Or perhaps the latest IDP was 3.6 only.

If we find a problem with using 3.6, then we definitely want to know about it, but I'm not too concerned that the latest desiconda installation tried using 3.6 instead of 3.5.  Testing against 3.6 at NERSC and 3.5 on travis might even be considered a feature... :)

If that informal "grab the latest stable version" policy becomes problematic, we can revisit how strict we need to be about package versions.  astropy is a current exception to that due to their habit of breaking APIs even with minor version bumps.  Hopefully that will stabilize in the 2.x series.
