### ISSUE TITLE
licenses shouldn't imply that we are the Astropy Team

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#91]
Somehow most of our repo licenses with BSD 3-clause got updated to include astropy-specific language in the 3rd clause:

> * Neither the name of the Astropy Team nor the names of its contributors may be used to endorse or promote products derived from this software without specific  prior written permission.

I'm not sure if that is required for astropy-affiliated packages, but it is out of place for most of or repos, which use astropy but are not developed by the Astropy Team.

The original BSD 3-clause wording should be find:

> * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

I suspect this was just a copy-and-paste propagation and not purposeful.
If you agree with reverting the wording to the original BSD 3-clause, please go ahead and update all of the repos without bothering to go via pull requests for each one.  If you disagree, let's chat about why...

**Comment by weaverba137** [comment]
PR #90 fixes this, so I'm going to go ahead & close.
