### ISSUE TITLE
desiInstall --root option only partially works (?)

### ISSUE THREAD

**Issue by sbailey** [desihub/desiutil#95]
This might just be user error / misunderstanding, but filing a ticket:

desiutil/1.9.9 desiInstall defaults to installing to the "new" location /global/common/software/desi/cori/desiconda/..., but for the desimodules 17.12 release I wanted to continue to use the old location of /global/common/cori/contrib/desi/desiconda/... .  I was expecting that the `desiInstall --root` option would be able to override that installation location.  IIRC, that worked for installing the code to the specified location, but it still put the module files in the default location (or perhaps vice-a-versa).

It sounds like I could have achieved a full install to a non-default location via a custom config file (see http://desiutil.readthedocs.io/en/latest/desiInstall.html#configuring-desiinstall), but it also seems like --root should have worked for this case to install to a different location.  If that isn't what --root is for, then I don't understand the purpose of that option.

**Comment by weaverba137** [comment]
`--root` overrides the value of `$DESI_PRODUCT_ROOT`, but at NERSC, the value of `$DESI_PRODUCT_ROOT` is ignored.

**Comment by weaverba137** [comment]
And, on detailed examination, the custom configuration file method overrides the *Module* install directory but not the *code* install directory.  

There is way too much second-guessing in desiInstall.

**Comment by sbailey** [comment]
Feel free to strip it down to simplify the second guessing.  In practice we only use it at NERSC so let's make it work well there.

**Comment by weaverba137** [comment]
Do you think it would be useful to poll desi-data to see how many people use desiInstall at locations other than NERSC, or at all?

**Comment by sbailey** [comment]
I'm pretty sure I know the answer, but go ahead and poll desi-data as a double check.

**Comment by weaverba137** [comment]
Indeed, I'm pretty sure I can predict the result too.

**Comment by weaverba137** [comment]
This should have been closed by #101.
