### ISSUE TITLE
Consider eliminating "cross-installs"

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiutil#96]
To reduce the complexity of desiInstall, consider eliminating "cross-installs".  A cross-install is where a product that contains no compiled code (*e.g.* only shell scripts and/or data) is installed only once and then symlinked into other install directories.  This has applied only to NERSC, where an install would be performed on edison, then symlinks would duplicate the installation for other NERSC hosts.

In practice, we don't actually use this that much, because we have very few products that fit into this category.  desimodules, desitree, and desiBackup are three products that do fit this category, but desimodules already requires special care in installation in the desiconda infrastructure.  So it doesn't seem worth it to carry forward the complexity of cross-installs just for a very small number of products.

@sbailey, please comment.

**Comment by sbailey** [comment]
+1

Go ahead and strip out cross-install support.
